// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khyflzkbwbfuhclijsxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeWZsemtid2JmdWhjbGlqc3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDY2NDEsImV4cCI6MjA1ODQ4MjY0MX0.1hhnKIya9WxqYlho7NCxVu6cXsEeDH1Ik-XLXHQHWEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);